fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [-i, --style=file:.clang-format]
  - repo: https://github.com/tomas-krupa/qmlformat-hook.git
    rev: 1.2.0
    hooks:
      - id: qmlformat
        args: [-i]
        additional_dependencies:
        - PySide6-Essentials==6.10.2
