name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 4.6.0.13
  TAILSCALE_VERSION: 1.96.4

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: armv7hl
            tailscale_arch: arm
          - arch: aarch64
            tailscale_arch: arm64
          - arch: i486
            tailscale_arch: 386

    steps:
    - uses: actions/checkout@v5

    - name: prepare
      run: mkdir RPMS

    - name: Build ${{ matrix.arch }}
      run: docker run --rm --privileged -v $PWD:/workspace coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            cd rpm ;
            curl -O https://pkgs.tailscale.com/stable/tailscale_${TAILSCALE_VERSION}_${{ matrix.tailscale_arch }}.tgz ;
            cd .. ;
            mb2 -t SailfishOS-$RELEASE-${{ matrix.arch }} build --prepare ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Upload build result
      uses: actions/upload-artifact@v5
      with:
        name: rpms-${{ matrix.arch }}
        path: RPMS
